/**
 * Central UI copy/text content registry for Tiny Universe.
 * Having all copy externalized in one place allows easy modifications and
 * keeps presentation concerns separate from components.
 */
export const CONTENT = {
  landingPage: {
    title: 'Tiny',
    titleAccent: ' Universe',
    subtitle: 'A cosmos of memories, just for you.',
    footer: 'Every memory becomes a planet in your universe ✦',
    accessLabel: 'Universe access',
    passcodePlaceholder: 'Enter passcode...',
    passcodeHint: 'Enter the secret passcode to unlock your universe',
    unlockBtn: 'Unlock Universe',
    unlockingBtn: 'Unlocking...',
    unlockAriaLabel: 'Unlock universe',
    unlockingAriaLabel: 'Verifying passcode...',
    welcomeToast: 'Welcome to your universe ✨',
    invalidPasscodeError: 'Invalid passcode',
    genericError: 'Something went wrong. Try again.',
  },
  universeList: {
    header: {
      title: 'Tiny',
      titleAccent: 'Universe',
      igniteBtn: 'Ignite Universe',
    },
    loader: 'Mapping the cosmos...',
    emptyState: {
      icon: '🛸',
      title: 'Your cosmos is currently void',
      subtitle: "You haven't created any universes yet. Ignite the first universe to start recording memories.",
      cta: 'Ignite Your First Universe',
    },
    grid: {
      createCard: {
        plus: '＋',
        title: 'Ignite New Universe',
        desc: 'Create a brand new shared digital universe',
      },
      card: {
        icon: '🪐',
        noDesc: 'No description provided.',
        created: 'Created:',
        editBtn: 'Edit',
        deleteBtn: 'Dissolve',
        infoTooltip: 'Show full description',
      },
    },
    igniteModal: {
      title: 'Ignite New Universe',
      fieldTitle: 'Universe Title *',
      fieldTitlePlaceholder: "e.g., Rakshith's Galaxy, Memory Lane",
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'What does this universe represent?',
      submitBtn: 'Ignite Cosmos',
      submitBtnLoading: 'Creating Universe...',
      successToast: 'New universe ignited ✨',
    },
    editModal: {
      title: 'Edit Universe Details',
      fieldTitle: 'Universe Title *',
      fieldTitlePlaceholder: "e.g., Rakshith's Galaxy, Memory Lane",
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'What does this universe represent?',
      submitBtn: 'Save Changes',
      submitBtnLoading: 'Saving...',
      successToast: 'Universe details updated ✨',
    },
    deleteModal: {
      title: 'Dissolve Universe',
      warningPrefix: 'Are you sure you want to dissolve the universe ',
      warningSuffix: '?',
      subtext:
        'This cosmic collapse is irreversible. All star systems, planets, and memories inside this universe will be permanently dissolved into the void.',
      cancelBtn: 'Cancel',
      confirmBtn: 'Dissolve Cosmos',
      successToast: 'Universe dissolved into stardust 🌑',
    },
    infoModal: {
      titlePrefix: 'About ',
      created: 'Created:',
      updated: 'Last Updated:',
      noDesc: 'No description provided.',
    },
  },
  systemsHub: {
    backBtn: '← Back to Universes',
    header: {
      title: 'Systems Hub',
      igniteBtn: 'Ignite Star System',
    },
    loader: 'Navigating stars...',
    emptyState: {
      icon: '🌌',
      title: 'This universe is empty of stars',
      subtitle: 'Create a star system to begin populating this universe with memories.',
      cta: 'Ignite Your First Star',
    },
    grid: {
      createCard: {
        plus: '＋',
        title: 'Ignite Star System',
        desc: 'Form a new solar system with a central star',
      },
      card: {
        icon: '☀️',
        noDesc: 'No description provided.',
        orbits: 'Orbits: ',
        planets: 'Planets: ',
        editBtn: 'Edit',
        deleteBtn: 'Dissolve',
        infoTooltip: 'Show system details',
        enterPrompt: 'Click to enter system ➔',
        starSystemSuffix: ' Star System',
      },
    },
    igniteModal: {
      title: 'Ignite Star System',
      fieldName: 'Star System Name *',
      fieldNamePlaceholder: 'e.g., Solar System, Alpha Centauri',
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'What stories live inside this star system?',
      fieldColor: 'Star Color',
      customColorLabel: 'Or choose custom color:',
      customColorPlaceholder: 'Hex Code (e.g. #F59E0B)',
      fieldType: 'Star Classification *',
      submitBtn: 'Ignite Star',
      submitBtnLoading: 'Creating Star System...',
      successToast: 'Star ignited and system formed! 🌟',
    },
    editModal: {
      title: 'Edit Star System Details',
      fieldName: 'Star System Name *',
      fieldNamePlaceholder: 'e.g., Solar System, Alpha Centauri',
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'What stories live inside this star system?',
      fieldColor: 'Star Color',
      customColorLabel: 'Or choose custom color:',
      customColorPlaceholder: 'Hex Code (e.g. #F59E0B)',
      fieldType: 'Star Classification *',
      submitBtn: 'Save Changes',
      submitBtnLoading: 'Saving...',
      successToast: 'Star system details updated ✨',
    },
    deleteModal: {
      title: 'Dissolve Star System',
      warningPrefix: 'Are you sure you want to dissolve the system ',
      warningSuffix: '?',
      subtext:
        'This cosmic collapse is irreversible. The star will collapse, and all memories (planets) in its orbits will be vaporized into stardust.',
      cancelBtn: 'Cancel',
      confirmBtn: 'Dissolve System',
      successToast: 'Star system dissolved into stardust 🌑',
    },
    infoModal: {
      noDesc: 'No description provided.',
      created: 'Created:',
      updated: 'Last Updated:',
      starTypeSuffix: ' Star System',
    },
    starColors: [
      { name: 'Amber Sun', value: '#FBBF24' },
      { name: 'Sky Giant', value: '#38BDF8' },
      { name: 'Pink Dwarf', value: '#F472B6' },
      { name: 'Crimson Giant', value: '#F87171' },
      { name: 'Emerald Nebula', value: '#34D399' },
      { name: 'Ametrine Star', value: '#8B5CF6' },
    ],
    starTypes: [
      { value: 'dwarf', name: 'Yellow Dwarf (Balanced)' },
      { value: 'giant', name: 'Blue Giant (Glows brightly)' },
      { value: 'supergiant', name: 'Red Supergiant (Massive)' },
      { value: 'nebula', name: 'Nebular Core (Mystical clouds)' },
      { value: 'pulsar', name: 'Pulsar Core (Dense and active)' },
    ],
  },
  systemCanvas: {
    backBtn: '← Back to Systems Hub',
    headerTitleSuffix: ' System',
    noMemories: 'No memories found. Click "Add Memory" to ignite a new planet in this system!',
    addMemoryBtn: '＋ Add Memory',
    newMemoryBtn: 'New Memory',
    loader: 'Drawing orbital lanes...',
    planetCount: (count: number) => `${count} ${count === 1 ? 'planet' : 'planets'}`,
    systemInLabel: 'System in',
  },
  addMemoryModal: {
    title: 'New Memory Planet',
    fieldTitle: 'Memory Title *',
    fieldTitlePlaceholder: 'What is this memory called?',
    fieldDate: 'Memory Date *',
    fieldOrbit: 'Orbit Ring *',
    orbitRings: [
      { value: 1, label: 'Ring 1 (Inner)' },
      { value: 2, label: 'Ring 2' },
      { value: 3, label: 'Ring 3' },
      { value: 4, label: 'Ring 4 (Outer)' },
    ],
    fieldDesc: 'Description (optional)',
    fieldDescPlaceholder: 'Tell the story of this memory...',
    submitBtn: 'Create Planet',
    submitBtnLoading: 'Creating planet...',
    successToast: 'Memory born into the universe 🪐',
    errorToast: 'Something went wrong. Try again.',
  },
  memoryModal: {
    orbitBadgePrefix: 'Orbit ',
    viewMode: {
      editBtn: '✏️ Edit',
      deleteBtn: '🗑️ Delete',
    },
    editMode: {
      fieldTitle: 'Title',
      fieldDate: 'Memory Date',
      fieldOrbit: 'Orbit Ring',
      fieldDesc: 'Description',
      cancelBtn: 'Cancel',
      saveBtn: 'Save Changes',
      saveBtnLoading: 'Saving...',
      successToast: 'Memory updated ✨',
      errorToast: 'Something went wrong. Try again.',
      orbitOptions: [
        { value: 1, label: 'Ring 1 (Inner)' },
        { value: 2, label: 'Ring 2' },
        { value: 3, label: 'Ring 3' },
        { value: 4, label: 'Ring 4 (Outer)' },
      ],
    },
    deleteConfirm: {
      icon: '🌑',
      title: 'Release this memory?',
      warningPrefix: '"',
      warningSuffix: '" will drift into the void and cannot be recovered.',
      cancelBtn: 'Keep it',
      confirmBtn: 'Yes, Release',
      confirmBtnLoading: 'Deleting...',
      successToast: 'Memory released into the void 🌑',
      errorToast: 'Something went wrong. Try again.',
    },
  },
  admin: {
    login: {
      title: 'Admin',
      titleAccent: ' Access',
      subtitle: 'Enter the master passcode to access the dashboard.',
      passcodePlaceholder: 'Enter master passcode...',
      unlockBtn: 'Access Dashboard',
      unlockingBtn: 'Authorizing...',
      invalidPasscodeError: 'Invalid master passcode',
      welcomeToast: 'Authenticated as Admin ✨',
    },
    dashboard: {
      title: 'Admin',
      titleAccent: ' Dashboard',
      subtitle: 'Manage universes, security access, and cosmic structures.',
      logoutBtn: 'Logout',
      createBtn: 'Ignite Universe',
      emptyState: {
        icon: '🌌',
        title: 'No Universes Found',
        subtitle: 'Create a new universe with a unique guest access passcode to begin.',
        cta: 'Create New Universe',
      },
      table: {
        headers: {
          name: 'Universe',
          slug: 'Slug',
          created: 'Created Date',
          systems: 'Solar Systems',
          memories: 'Memories',
          actions: 'Actions',
        },
      },
      cards: {
        openBtn: 'Open ➔',
        copyLinkBtn: 'Copy Link',
        editBtn: 'Edit',
        deleteBtn: 'Dissolve',
        linkCopiedToast: 'Universe link copied to clipboard 📋',
      },
    },
    createModal: {
      title: 'Ignite New Universe',
      fieldName: 'Universe Name *',
      fieldNamePlaceholder: 'e.g., Family Archive, Our Space',
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'Describe the contents of this universe...',
      fieldCode: 'Guest Access Code *',
      fieldCodePlaceholder: 'e.g., fam2026',
      submitBtn: 'Ignite Universe',
      submitBtnLoading: 'Igniting...',
      successToast: 'Universe successfully created ✨',
    },
    editModal: {
      title: 'Edit Universe Details',
      fieldName: 'Universe Name *',
      fieldNamePlaceholder: 'e.g., Family Archive, Our Space',
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'Describe the contents of this universe...',
      fieldCode: 'New Guest Access Code (optional)',
      fieldCodePlaceholder: 'Leave blank to keep current code',
      submitBtn: 'Save Details',
      submitBtnLoading: 'Saving...',
      successToast: 'Universe details updated ✨',
    },
    deleteModal: {
      title: 'Dissolve Universe',
      warningPrefix: 'Are you sure you want to permanently dissolve ',
      warningSuffix: '?',
      subtext: 'This action cannot be undone. All systems, stars, planets, and memories inside this universe will be vaporized.',
      cancelBtn: 'Keep Universe',
      confirmBtn: 'Dissolve Universe',
      successToast: 'Universe dissolved into stardust 🌑',
    },
  },
  guestUnlock: {
    title: 'Unlock',
    titleAccent: ' Universe',
    subtitle: 'This universe is protected. Please enter the guest access code to enter.',
    passcodePlaceholder: 'Enter access code...',
    unlockBtn: 'Unlock Universe',
    unlockingBtn: 'Unlocking...',
    invalidPasscodeError: 'Invalid guest access code',
    welcomeToast: 'Universe unlocked! Welcome ✨',
  },
  canvas: {
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    recenter: 'Recenter View',
  },
  common: {
    loading: 'Loading...',
    closeBtn: '✕',
    genericError: 'Something went wrong. Try again.',
  },
} as const;
