/**
 * Central UI copy/text content registry for Tiny Universe.
 * Having all copy externalized in one place allows easy modifications and
 * keeps presentation concerns separate from components.
 */
export const CONTENT = {
  metadata: {
    layout: {
      title: 'Tiny Universe | Your Memory Galaxy',
      description:
        'A shared digital universe where every memory becomes a planet floating in space. Create, explore, and cherish your memories in a beautiful starfield.',
      keywords: ['memories', 'universe', 'space', 'journal', 'personal'],
      openGraph: {
        title: 'Tiny Universe | Your Memory Galaxy',
        description: 'Every memory is a planet. Explore your universe.',
        type: 'website' as const,
      },
    },
    page: {
      title: 'Tiny Universe | Digital Cosmos of Shared Memories',
      description: 'Every memory becomes a planet in your universe ✦',
    },
  },
  landingPage: {
    footer: 'Every memory becomes a planet in your universe ✦',
    notFoundTitle: '404',
    notFoundSubtitle: 'Universe not found',
    returnToLanding: 'Return to Landing Page',
  },
  universeList: {
    loader: 'Mapping the cosmos...',
    grid: {
      card: {
        noDesc: 'No description provided.',
      },
    },
  },
  systemsHub: {
    backToDashboard: 'Dashboard',
    backToDashboardAria: 'Back to Admin Dashboard',
    universeTitlePrefix: 'Universe: ',
    header: {
      title: 'Systems Hub',
      igniteBtn: 'Ignite Star System',
      igniteBtnMobile: 'Ignite',
    },
    loader: 'Navigating stars...',
    emptyState: {
      icon: '🌌',
      title: 'This universe is empty of stars',
      subtitle: 'Create a star system to begin populating this universe with memories.',
      cta: 'Ignite Your First Star',
    },
    grid: {
      createCard: {
        plus: '＋',
        title: 'Ignite Star System',
        desc: 'Form a new solar system with a central star',
      },
      card: {
        icon: '☀️',
        noDesc: 'No description provided.',
        editBtn: 'Edit',
        deleteBtn: 'Dissolve',
        infoTooltip: 'Show system details',
        enterPrompt: 'Click to enter system ➔',
        enterSystemAria: (name: string) => `Enter system ${name}`,
        editSystemAria: (name: string) => `Edit ${name}`,
        dissolveSystemAria: (name: string) => `Dissolve ${name}`,
        dissolveSystemDisabledTooltip: 'Only Admin can dissolve systems',
      },
    },
    igniteModal: {
      title: 'Ignite Star System',
      fieldName: 'Star System Name *',
      fieldNamePlaceholder: 'e.g., Solar System, Alpha Centauri',
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'What stories live inside this star system?',
      fieldColor: 'Star Color',
      customColorLabel: 'Or choose custom color:',
      customColorPlaceholder: 'Hex Code (e.g. #F59E0B)',
      fieldType: 'Star Classification *',
      submitBtn: 'Ignite Star',
      submitBtnLoading: 'Creating Star System...',
      successToast: 'Star ignited and system formed! 🌟',
    },
    editModal: {
      title: 'Edit Star System Details',
      fieldName: 'Star System Name *',
      fieldNamePlaceholder: 'e.g., Solar System, Alpha Centauri',
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'What stories live inside this star system?',
      fieldColor: 'Star Color',
      customColorLabel: 'Or choose custom color:',
      customColorPlaceholder: 'Hex Code (e.g. #F59E0B)',
      fieldType: 'Star Classification *',
      submitBtn: 'Save Changes',
      submitBtnLoading: 'Saving...',
      successToast: 'Star system details updated ✨',
    },
    deleteModal: {
      title: 'Dissolve Star System',
      warningPrefix: 'Are you sure you want to dissolve the system ',
      warningSuffix: '?',
      subtext:
        'This cosmic collapse is irreversible. The star will collapse, and all memories (planets) in its orbits will be vaporized into stardust.',
      cancelBtn: 'Cancel',
      confirmBtn: 'Dissolve System',
      confirmBtnLoading: 'Dissolving...',
      successToast: 'Star system dissolved into stardust 🌑',
    },
    infoModal: {
      noDesc: 'No description provided.',
      created: 'Created:',
      updated: 'Last Updated:',
    },
    starColors: [
      { name: 'Amber Sun', value: '#FBBF24' },
      { name: 'Sky Giant', value: '#38BDF8' },
      { name: 'Pink Dwarf', value: '#F472B6' },
      { name: 'Crimson Giant', value: '#F87171' },
      { name: 'Emerald Nebula', value: '#34D399' },
      { name: 'Ametrine Star', value: '#8B5CF6' },
    ],
    starTypes: [
      { value: 'dwarf', name: 'Yellow Dwarf (Balanced)' },
      { value: 'giant', name: 'Blue Giant (Glows brightly)' },
      { value: 'supergiant', name: 'Red Supergiant (Massive)' },
      { value: 'nebula', name: 'Nebular Core (Mystical clouds)' },
      { value: 'pulsar', name: 'Pulsar Core (Dense and active)' },
    ],
  },
  systemCanvas: {
    backBtn: '← Back to Systems Hub',
    backToSystemsLabel: 'Systems',
    addMemoryBtn: '＋ Add Memory',
    newMemoryBtn: 'New Memory',
    loader: 'Drawing orbital lanes...',
    planetCount: (count: number) => `${count} ${count === 1 ? 'planet' : 'planets'}`,
    systemInUniverse: (name: string) => `System in ${name} Universe`,
    loadingSystem: 'Loading System...',
  },
  emptyState: {
    ariaLabel: 'Empty universe',
    title: 'Your universe is empty.',
    descriptionLine1: 'Every memory is a planet waiting to be born.',
    descriptionLine2: 'Create your first one and watch your universe come alive.',
    ariaLabelCta: 'Create your first memory',
    cta: 'Create First Memory',
  },
  addMemoryModal: {
    title: 'New Memory Planet',
    fieldTitle: 'Memory Title *',
    fieldTitlePlaceholder: 'What is this memory called?',
    fieldContributor: 'Your Name * (Min 4 characters)',
    fieldContributorPlaceholder: 'Enter your name...',
    fieldContributorMinError: 'Name must be at least 4 characters',
    fieldDate: 'Memory Date *',
    fieldOrbit: 'Orbit Ring *',
    orbitRings: [
      { value: 1, label: 'Ring 1 (Inner)' },
      { value: 2, label: 'Ring 2' },
      { value: 3, label: 'Ring 3' },
      { value: 4, label: 'Ring 4 (Outer)' },
    ],
    fieldDesc: 'Description (optional)',
    fieldDescPlaceholder: 'Tell the story of this memory...',
    submitBtn: 'Create Planet',
    submitBtnLoading: 'Creating planet...',
    successToast: 'Memory born into the universe 🪐',
    errorToast: 'Something went wrong. Try again.',
  },
  memoryModal: {
    orbitBadgePrefix: 'Orbit ',
    viewMode: {
      editBtn: 'Edit',
      deleteBtn: 'Dissolve',
      deleteBtnTooltip: 'Only Admin can dissolve memories',
      addedBy: (name: string) => `Added by ${name}`,
    },
    editMode: {
      fieldTitle: 'Title',
      fieldContributor: 'Your Name * (Min 4 characters)',
      fieldContributorMinError: 'Name must be at least 4 characters',
      fieldDate: 'Memory Date',
      fieldOrbit: 'Orbit Ring',
      fieldDesc: 'Description',
      cancelBtn: 'Cancel',
      saveBtn: 'Save Changes',
      saveBtnLoading: 'Saving...',
      successToast: 'Memory updated ✨',
      errorToast: 'Something went wrong. Try again.',
      orbitOptions: [
        { value: 1, label: 'Ring 1 (Inner)' },
        { value: 2, label: 'Ring 2' },
        { value: 3, label: 'Ring 3' },
        { value: 4, label: 'Ring 4 (Outer)' },
      ],
    },
    deleteConfirm: {
      icon: '🌑',
      title: 'Release this memory?',
      warningPrefix: '"',
      warningSuffix: '" will drift into the void and cannot be recovered.',
      cancelBtn: 'Keep it',
      confirmBtn: 'Yes, Release',
      confirmBtnLoading: 'Deleting...',
      successToast: 'Memory released into the void 🌑',
      errorToast: 'Something went wrong. Try again.',
    },
  },
  admin: {
    login: {
      title: 'Admin',
      titleAccent: ' Access',
      subtitle: 'Enter the master passcode to access the dashboard.',
      passcodePlaceholder: 'Enter master passcode...',
      unlockBtn: 'Access Dashboard',
      unlockingBtn: 'Authorizing...',
      invalidPasscodeError: 'Invalid master passcode',
      welcomeToast: 'Authenticated as Admin ✨',
    },
    dashboard: {
      title: 'Admin',
      titleAccent: ' Dashboard',
      subtitle: 'Manage universes, security access, and cosmic structures.',
      logoutBtn: 'Logout',
      logoutBtnMobile: 'Logout',
      logoutSuccess: 'Logged out successfully',
      logoutFailed: 'Logout failed',
      sectionTitle: 'Admin Dashboard',
      createBtn: 'Ignite Universe',
      createBtnMobile: 'Ignite',
      createCardDesc: 'Form a new universe with access codes',
      slugLabel: 'Slug:',
      solarSystemsLabel: 'Solar Systems',
      memoriesLabel: 'Memories',
      emptyState: {
        icon: '🌌',
        title: 'No Universes Found',
        subtitle: 'Create a new universe with a unique guest access passcode to begin.',
        cta: 'Create New Universe',
      },
      cards: {
        openBtn: 'Open ➔',
        copyLinkBtn: 'Copy Link',
        editBtn: 'Edit',
        deleteBtn: 'Dissolve',
        linkCopiedToast: 'Universe link copied to clipboard 📋',
      },
    },
    createModal: {
      title: 'Ignite New Universe',
      fieldName: 'Universe Name *',
      fieldNamePlaceholder: 'e.g., Family Archive, Our Space',
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'Describe the contents of this universe...',
      fieldCode: 'Guest Access Code *',
      fieldCodePlaceholder: 'e.g., fam2026',
      submitBtn: 'Ignite Universe',
      submitBtnLoading: 'Igniting...',
      successToast: 'Universe successfully created ✨',
      slugPreview: 'Slug preview:',
    },
    editModal: {
      title: 'Edit Universe Details',
      fieldName: 'Universe Name *',
      fieldNamePlaceholder: 'e.g., Family Archive, Our Space',
      fieldDesc: 'Description (optional)',
      fieldDescPlaceholder: 'Describe the contents of this universe...',
      fieldCode: 'New Guest Access Code (optional)',
      fieldCodePlaceholder: 'Leave blank to keep current code',
      submitBtn: 'Save Details',
      submitBtnLoading: 'Saving...',
      successToast: 'Universe details updated ✨',
      slugPreview: 'New slug preview:',
    },
    deleteModal: {
      title: 'Dissolve Universe',
      warningPrefix: 'Are you sure you want to permanently dissolve ',
      warningSuffix: '?',
      subtext: 'This action cannot be undone. All systems, stars, planets, and memories inside this universe will be vaporized.',
      cancelBtn: 'Keep Universe',
      confirmBtn: 'Dissolve Universe',
      confirmBtnLoading: 'Dissolving...',
      successToast: 'Universe dissolved into stardust 🌑',
    },
  },
  guestUnlock: {
    title: 'Unlock',
    titleAccent: ' Universe',
    subtitle: 'This universe is protected. Please enter the guest access code to enter.',
    passcodePlaceholder: 'Enter access code...',
    unlockBtn: 'Unlock Universe',
    unlockingBtn: 'Unlocking...',
    invalidPasscodeError: 'Invalid guest access code',
    welcomeToast: 'Universe unlocked! Welcome ✨',
  },
  canvas: {
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    recenter: 'Recenter View',
    planetAriaLabel: (title: string, date: string) => `Planet: ${title}. Created on ${date}. Click to view memory.`,
    planetTitle: (title: string, date: string) => `${title} (${date})`,
  },
  common: {
    loading: 'Loading...',
    closeBtn: '✕',
    genericError: 'Something went wrong. Try again.',
  },
  api: {
    errors: {
      unauthorized: 'Unauthorized',
      notFound: {
        universe: 'Universe not found',
        solarSystem: 'Solar system not found',
        memory: 'Memory not found',
      },
      required: {
        systemId: 'systemId is required',
        universeId: 'universeId is required',
        universeIdParam: 'universeId query parameter is required',
        title: 'Title is required',
        date: 'Date is required',
        name: 'Name is required',
        passcode: 'Passcode is required',
        slug: 'Universe slug is required',
        accessCode: 'Access code is required',
        param: 'Parameter is required',
      },
      validation: {
        titleTooLong: 'Title cannot exceed 100 characters',
        descTooLong1000: 'Description cannot exceed 1000 characters',
        descTooLong500: 'Description too long',
        nameTooLong: 'Name too long',
      },
      server: {
        config: 'Server configuration error',
        internal: 'Internal server error',
        fetchUniverse: 'Failed to fetch universe',
        fetchUniverses: 'Failed to fetch universes',
        createUniverse: 'Failed to create universe',
        updateUniverse: 'Failed to update universe',
        deleteUniverse: 'Failed to delete universe',
        fetchSolarSystems: 'Failed to fetch solar systems',
        createSolarSystem: 'Failed to create solar system',
        updateSolarSystem: 'Failed to update solar system',
        deleteSolarSystem: 'Failed to dissolve solar system',
        fetchMemories: 'Failed to fetch memories',
        createMemory: 'Failed to create memory',
        updateMemory: 'Failed to update memory',
        deleteMemory: 'Failed to delete memory',
        clearSession: 'Failed to clear session',
      },
    },
  },
} as const;
